menu:
- {name: 'blog', url: '/blog'}
- {name: 'equipment', url: '/equipment'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/erikjrz'}
- {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/erikjrz'}

